/**
 * Travista PDF Export Service
 * Generates a clean, professional travel itinerary PDF using jsPDF.
 */

import { jsPDF } from 'jspdf';

// ─── Colour Palette ──────────────────────────────────────────────────────────
const C = {
  emerald:  [29, 158, 117],   // brand accent
  dark:     [17,  24,  39],   // gray-900
  mid:      [75,  85,  99],   // gray-600
  muted:    [156, 163, 175],  // gray-400
  light:    [249, 250, 251],  // gray-50
  border:   [229, 231, 235],  // gray-200
  white:    [255, 255, 255],
  purple:   [109,  40, 217],
  amber:    [180, 120,  10],
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Safely truncate text so jsPDF never crashes on undefined */
const s = (v, fallback = '') => (typeof v === 'string' && v.trim() ? v : fallback);

/** Wrap text and return array of lines, capped to maxLines */
const wrapLines = (doc, text, maxWidth, maxLines = 99) =>
  doc.splitTextToSize(s(text, '—'), maxWidth).slice(0, maxLines);

/** Draw a thin horizontal rule */
const rule = (doc, y, leftX, rightX, color = C.border) => {
  doc.setDrawColor(...color);
  doc.setLineWidth(0.2);
  doc.line(leftX, y, rightX, y);
};

/** Filled rounded rectangle */
const filledRect = (doc, x, y, w, h, r, rgb) => {
  doc.setFillColor(...rgb);
  doc.roundedRect(x, y, w, h, r, r, 'F');
};

/** Small pill label */
const pill = (doc, x, y, text, bg, fg) => {
  const pad = 3;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  const tw = doc.getTextWidth(text);
  filledRect(doc, x, y - 4, tw + pad * 2, 6.5, 1.5, bg);
  doc.setTextColor(...fg);
  doc.text(text, x + pad, y + 0.5);
};

// ─── Main Export Function ─────────────────────────────────────────────────────

/**
 * @param {object} plan  - The AI-generated itinerary object
 * @returns {void}       - Triggers browser download automatically
 */
export async function downloadItineraryPDF(plan) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const PW = doc.internal.pageSize.getWidth();   // 210
  const PH = doc.internal.pageSize.getHeight();  // 297
  const ML = 18, MR = 18;                         // left / right margin
  const CW = PW - ML - MR;                        // content width
  let y = 0;

  // ── Helper: new page guard ────────────────────────────────────────────────
  const checkPage = (needed = 10) => {
    if (y + needed > PH - 16) {
      doc.addPage();
      y = 18;
      drawPageFooter();
    }
  };

  // ── Footer (repeated on every page) ──────────────────────────────────────
  const drawPageFooter = () => {
    const py = PH - 10;
    rule(doc, py - 3, ML, PW - MR);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.muted);
    doc.text('Generated by Travista AI  ·  travista.app', ML, py);
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, PW - MR, py, { align: 'right' });
  };

  // ── 1. Cover Header ───────────────────────────────────────────────────────
  filledRect(doc, 0, 0, PW, 46, 0, C.dark);

  // Logo word-mark
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...C.emerald);
  doc.text('TRAVISTA', ML, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text('AI Travel Planner', ML, 18);

  // Trip title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...C.white);
  const titleLines = wrapLines(doc, s(plan.title, 'Your Itinerary'), CW, 2);
  doc.text(titleLines, ML, 30);

  // Generation date (top-right)
  const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.text(dateStr, PW - MR, 13, { align: 'right' });

  y = 54;

  // ── 2. Summary ────────────────────────────────────────────────────────────
  if (plan.summary) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(...C.mid);
    const summLines = wrapLines(doc, plan.summary, CW, 4);
    doc.text(summLines, ML, y);
    y += summLines.length * 5 + 6;
  }

  // ── 3. Meta Pills ────────────────────────────────────────────────────────
  if (plan.bestSeason || plan.budget || plan.weather) {
    const meta = [
      plan.bestSeason && `🗓 ${plan.bestSeason}`,
      plan.budget     && `💰 ${plan.budget}`,
      plan.weather    && `🌤 ${plan.weather}`,
    ].filter(Boolean);

    let mx = ML;
    meta.forEach(m => {
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      const tw = doc.getTextWidth(m) + 8;
      filledRect(doc, mx, y - 4, tw, 7, 1.5, C.light);
      doc.setDrawColor(...C.border);
      doc.setLineWidth(0.2);
      doc.roundedRect(mx, y - 4, tw, 7, 1.5, 1.5, 'S');
      doc.setTextColor(...C.mid);
      doc.text(m, mx + 4, y + 0.5);
      mx += tw + 4;
    });
    y += 12;
  }

  rule(doc, y, ML, PW - MR, C.emerald);
  y += 8;

  // ── 4. Day-by-Day Timeline ────────────────────────────────────────────────
  if (plan.days?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...C.dark);
    doc.text('DAY-BY-DAY ITINERARY', ML, y);
    y += 7;

    plan.days.forEach((day, di) => {
      checkPage(32);

      // Day badge strip
      filledRect(doc, ML, y, CW, 8.5, 2, C.dark);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...C.emerald);
      doc.text(`Day ${day.day}`, ML + 4, y + 5.5);
      doc.setTextColor(...C.white);
      doc.text(s(day.title, ''), ML + 18, y + 5.5);
      y += 12;

      // Morning / Afternoon / Evening
      const slots = [
        { label: 'Morning',   emoji: '🌅', text: day.morning },
        { label: 'Afternoon', emoji: '☀️', text: day.afternoon },
        { label: 'Evening',   emoji: '🌙', text: day.evening },
      ].filter(slot => slot.text);

      slots.forEach(slot => {
        checkPage(14);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(...C.emerald);
        doc.text(`${slot.emoji} ${slot.label}`, ML + 3, y);

        const lines = wrapLines(doc, slot.text, CW - 6, 4);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...C.mid);
        doc.text(lines, ML + 3, y + 4.5);
        y += 4.5 + lines.length * 4.2 + 3;
      });

      // Stay + Food on one row
      checkPage(10);
      const infoRow = [
        day.stay && `🛏 ${s(day.stay)}`,
        day.food && `🍽 ${s(day.food)}`,
      ].filter(Boolean);

      if (infoRow.length) {
        filledRect(doc, ML, y, CW, 8, 1.5, C.light);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...C.mid);
        doc.text(infoRow.join('    '), ML + 3, y + 5);
        y += 11;
      }

      // Thin divider between days (except last)
      if (di < plan.days.length - 1) {
        checkPage(6);
        rule(doc, y, ML, PW - MR);
        y += 6;
      }
    });
  }

  // ── 5. Insider Tips ───────────────────────────────────────────────────────
  if (plan.tips?.length) {
    checkPage(20);
    y += 6;
    rule(doc, y, ML, PW - MR, C.emerald);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...C.dark);
    doc.text('INSIDER TIPS', ML, y);
    y += 7;

    plan.tips.forEach(tip => {
      checkPage(10);
      const lines = wrapLines(doc, tip, CW - 6, 3);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...C.mid);
      doc.setDrawColor(...C.emerald);
      doc.setFillColor(...C.emerald);
      doc.circle(ML + 1.5, y - 1, 1, 'F');
      doc.text(lines, ML + 5, y);
      y += lines.length * 4.2 + 3;
    });
  }

  // ── 6. Hidden Gems ────────────────────────────────────────────────────────
  if (plan.hiddenGems?.length) {
    checkPage(20);
    y += 4;
    rule(doc, y, ML, PW - MR);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...C.dark);
    doc.text('HIDDEN GEMS', ML, y);
    y += 6;

    let gx = ML;
    plan.hiddenGems.forEach(gem => {
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      const tw = doc.getTextWidth(gem) + 8;
      if (gx + tw > PW - MR) { gx = ML; y += 8; checkPage(8); }
      filledRect(doc, gx, y - 4, tw, 6.5, 1.5, [237, 233, 254]); // purple-100
      doc.setDrawColor(...[196, 181, 253]);
      doc.setLineWidth(0.2);
      doc.roundedRect(gx, y - 4, tw, 6.5, 1.5, 1.5, 'S');
      doc.setTextColor(...C.purple);
      doc.text(gem, gx + 4, y + 0.5);
      gx += tw + 4;
    });
    y += 10;
  }

  // ── 7. Footer on last page ────────────────────────────────────────────────
  drawPageFooter();

  // ── 8. Save ───────────────────────────────────────────────────────────────
  const slug = s(plan.title, 'itinerary')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 40);

  doc.save(`${slug}-travista.pdf`);
}
